title: Balaji's Weblog
email: damodaran.balaji@gmail.com
description: >-
  Life and times of Balaji Damodaran
baseurl: ""
url: "https://balaji.dev"
repository: balaji/balaji.github.io
instagram: balajid.v4
github: balaji
author: Balaji Damodaran
author_bio: >-
  I make my living by writing software for large companies. As the title of this site suggests,
  I lived <a href="/42-year-career">at least 50%</a> of my life, so it wasn't all bad. I raise two daughters and a cat in the beautiful
  city of Stockholm, Sweden.
author_pic: https://avatars.githubusercontent.com/u/137302?v=4

paginate: 20
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-target-blank
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layout: tags
  permalinks:
    tag: '/tags/:name/'
permalink: /:title

theme_switcher: false

collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
