title: Balaji - Personal Blog
author:
  name: Balaji Damodaran
  email: damodaran.balaji@gmail.com
description: >-
  The life and times of me in longform text.<br/>
  ஆறடி உயரம். பருத்த உடல். கருத்த மாநிறம்.
baseurl: ""
url: "https://balaji.dev"
github_username:  balaji
google_analytics: G-Z5R0VK62EK

markdown: kramdown
usemathjax: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto"
  back_home_text: "back"
  date_format: "%Y-%m-%d"
  show_description: false # show blog description in home page
paginate: 5

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
